#!/bin/sh
lock() {
    i3lock -i /lhome/chrrist/dotfiles/assets/wide_ultra_ocean_by_ocean_trevor_mccarthy_scaled.png
}

turn_off_monitor() {
    xset dpms force standby
}

case "$1" in
    turn_off)
        turn_off_monitor
        ;;
    lock)
        turn_off_monitor && lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
        exit 2
esac

exit 
